export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const ERROR = "ERROR";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const INCREMENT_NUMBER_OF_ITEM_IN_CART =
  "INCREMENT_NUMBER_OF_ITEM_IN_CART";
export const DECREMENT_NUMBER_OF_ITEM_IN_CART =
  "IDECREMENT_NUMBER_OF_ITEM_IN_CART";
export const GET_CART = "GET_CART";
